### ISSUE TITLE
eulerr not working with r 4.2.0

### ISSUE THREAD

**Issue by sdavidsson90** [jolars/eulerr#100]
I am not able to install eulerr on R 4.2.0. It works fine on 4.1.2. 
I suspect this has something to do with the GenSA package, as I am getting the following error message:
`installation of package ‘GenSA’ had non-zero exit status`

I hope I am submitting this to the correct channel.

regards
Sighvatur Davidsson

**Comment by jolars** [comment]
Thanks, but I don't think this belongs here. There's probably more to the error message than that, right? Check the full log for more information.

Looking at https://cran.r-project.org/web/checks/check_results_GenSA.html, it seems like GenSA is building fine on all of the CRAN test systems, so maybe this is related to something on your end?
