### ISSUE TITLE
Overlap of four sets is missing observations

### ISSUE THREAD

**Issue by mcsimenc** [jolars/eulerr#103]
For this case of four overlapping sets, the `plot` diagram misses A&D and D.
![image](https://user-images.githubusercontent.com/7388518/201761534-6405a8a8-c53c-4c06-b2b0-554fe02ce7eb.png)

The sets A,B,C,D are available here: https://www.dropbox.com/sh/4etahhvv4lvjif8/AADIgE3T844zI3zfrGwh_luIa?dl=0

Code:
```
eulerList = list("A" = charVecA, "B" = charVecB, "C" = charVecC, "D" = charVecD)

eulerResult = euler(eulerList, shape = "ellipse")

plot(eulerResult, labels = F, quantities = T, legend = T, main = "Sets A,B,C,D", fills = c("#00a0d1", "#34ebcf", "#e86868"))
```

The underlying euler() result shows the correct overlaps:
```
eulerResult$original.values
      A       B       C       D     A&B     A&C     A&D     B&C     B&D     C&D   A&B&C   A&B&D   A&C&D   B&C&D A&B&C&D 
     26     455      86      26      10       6       4      34      56      21       2       8      13      79      51
```

Repeatedly running the above code occasionally results in a plot with the correct sections:
![image](https://user-images.githubusercontent.com/7388518/201809781-6ebe785f-f053-435d-ac20-e99014e4c3c5.png)
Still, for other cases I'm working with it never seems to plot a diagram with correct overlaps shown.

Are there sets for which the overlaps are impossible to capture in a `eulerr` plot? If so is there a way to know when this would be the case without manually checking overlaps?

Could there be some way to run `euler` + `plot` iteratively, checking overlaps at each step by summing the plot labels and plotting only when the correct number of observations would be shown? A clue for the first plot is the overlapping colors are not as expected (white though overlapping).

**Comment by jolars** [comment]
There is not in general an exact solution to 4-set diagrams. eulerr uses numerical optimization to find a good approximation in these cases. Even then, the objective is non-convex so there are multiple local minimi that one might get stuck in.

> Repeatedly running the above code occasionally results in a plot with the correct sections:

Sure, but that doesn't mean that the loss is lower for this fit. I am working on adding multiple loss metrics, some of which will penalize missing intersections more, however.

> Are there sets for which the overlaps are impossible to capture in a eulerr plot? 

Yes, absolutely. The package does not guarantee that the fit is exact.

> If so is there a way to know when this would be the case without manually checking overlaps?

I don't know of any analytical way, although it of course generally gets harder the more and larger the intersections between many sets are.

> Could there be some way to run euler + plot iteratively, checking overlaps at each step by summing the plot labels and plotting only when the correct number of observations would be shown? A clue for the first plot is the overlapping colors are not as expected (white though overlapping).

There is no guarantee that there is an exact solution, so this would guarantee anything. But it would be straightforward to do something like this to increase the likelihood of finding the global minimum. You can also try using the more powerful, but slower, optimizer through `extra.args`.
