### ISSUE TITLE
Getting an error: Error in f(x, ...) : Mat::min(): object has no elements

### ISSUE THREAD

**Issue by ndrubins** [jolars/eulerr#11]
Hi,

I'm trying to produce a Venn digram for a set of combinations, given as a named vector:

```
vals <- c(329,88,3,40,12,2,330,5,25,4,1,22,17,2,1,540,18,7,11,3,3,1,1,1,3,32,7,69,5,2,3,396,14,5,1,1,18,1,5,1,3,21,8,1,40,23,1,37,11,754,288,561,66,3,167,3,35,599,18,8,2,5,1,2,1,1,56,4,1,1,3,2,2,10,1,1,14,4,1,6,1,2,42,6,27,11,4,1,747,17,4,7,2,13,7,4,63,2,3,5,22,8,2,117,4,2,2,1,5,15,5,26,3,80,1,3,17,42,20,1,74,66,3,9,5)
names(vals) <- c("a.1&c.1&b.1&d.1&e.1","a.1&c.1&b.1&d.1","a.1&b.1&d.1&e.1","a.1&c.1&d.1&e.1","a.1&c.1&b.1&e.1","a.1&c.1&e.1&f.1","c.1&b.1&d.1&e.1","a.1&c.1&e.1","a.1&b.1&d.1","a.1&d.1&e.1","a.1&c.1&b.1","a.1&c.1&d.1","a.1&b.1&e.1","c.1&b.1&d.1","c.1&b.1&e.1","c.1&d.1&e.1","b.1&d.1&e.1","a.0&b.1&d.1&e.1","a.0&c.1&d.1&e.1","a.1&c.1&b.1&e.0","c.0&b.1&d.1&e.1","a.0&c.0&b.1&d.1&e.1","a.1&e.1","a.1&b.1","a.1&c.1","a.1&d.1","c.1&b.1","c.1&d.1","c.1&e.1","c.1&f.1","b.1&e.1","b.1&d.1","d.1&e.1","a.0&b.1&e.1","a.0&b.1&d.1","a.0&c.1&d.1","a.0&d.1&e.1","a.1&c.1&e.0","a.0&c.1&e.1","a.1&b.1&e.0","a.0&c.1&b.1","a.1&b.0&e.1","a.1&c.1&d.0","a.0&e.1&f.1","c.0&b.1&e.1","c.0&b.1&d.1","c.0&e.1&f.1","c.1&d.1&e.0","a.0&c.0&b.1&e.1","a.0&c.1&d.1&e.0","a.0&c.0&b.1&d.1","a.1&c.1&b.0&e.0","a.1","c.1","b.1","d.1","e.1","f.1","a.0&e.1","a.0&b.1","a.0&d.1","a.0&c.1","a.1&e.0","a.1&b.0","a.1&c.0","a.1&d.0","c.0&e.1","c.1&b.0","c.0&d.1","c.1&d.0","c.1&e.0","c.0&b.1","b.0&e.1","b.1&e.0","b.0&d.1","b.1&d.0","d.0&e.1","d.1&e.0","a.0&c.0&e.1","a.0&c.0&b.1","a.0&c.1&e.0","a.1&d.0&e.0","a.1&b.0&e.0","a.1&c.0&e.0","a.0&c.0&d.1","c.0&d.1&e.0","c.1&b.0&d.0","c.1&b.0&e.0","c.0&b.0&e.1","c.0&b.0&d.1","b.0&d.1&e.0","c.1&b.0&d.0&e.0","a.1&c.0&b.0&d.0&e.0","a.0","c.0","b.0","d.0","e.0","f.0","a.0&c.0","a.0&e.0","a.0&d.0","a.0&b.0","c.0&b.0","c.0&d.0","c.0&e.0","b.0&e.0","b.0&d.0","d.0&e.0","a.0&c.0&d.0","a.0&c.0&b.0","a.0&c.0&e.0","a.0&b.0&e.0","a.0&d.0&e.0","c.0&d.0&e.0","c.0&b.0&e.0","c.0&b.0&d.0","b.0&d.0&e.0","a.0&c.0&d.0&e.0","a.0&c.0&b.0&d.0","a.0&c.0&b.0&e.0","a.0&b.0&d.0&e.0","a.0&c.0&e.0&f.0","c.0&b.0&d.0&e.0","a.0&c.0&b.0&d.0&e.0")


```
Running:
`euler.obj <- eulerr::euler(vals)
`
Throws this error:
`Error in f(x, ...) : Mat::min(): object has no elements
`

Any idea?

Thanks

**Comment by jolars** [comment]
Are you running the development version or the cran release?

**Comment by ndrubins** [comment]
I'm running:
`eulerr_2.0.0
`

**Comment by ndrubins** [comment]
Just installed the github version:
`devtools::install_github("jolars/eulerr")
`
But still getting the same error

**Comment by jolars** [comment]
Yeah this is probably some error in the intersection computations. 

Try `devtools::install_github("jolars/eulerr", ref = "ellipses")` to install the branch that I'm currently working on and see if works there. However, if I'm counting correctly, you are trying to fit 12 sets. I'm trying to fit the configuration now and, though it's not throwing any errors, it's taking forever and is most likely not going to yield any decent solution.

**Comment by jolars** [comment]
I merged the ellipses branch into master now and the error should be gone.

**Comment by ndrubins** [comment]
Thanks a lot @jolars,
It doesn't crash anymore, but I guess my data is too challenging for a Venn diagram. The plot comes out misleading. For example, it f.0 and f.1 seem to have an overlap in the plot but that intersection doesn't exist in the `vals` vector. Any suggestions?

**Comment by jolars** [comment]
Yeah, that is often the case with 3+ sets. You could either try with `shape=ellipse` (but it's going to be even slower), or I suggest you try [UpSetR](https://cran.r-project.org/web/packages/UpSetR/index.html), which is
great for large set combinations.
