### ISSUE TITLE
Can't intall under R version 4.3.0

### ISSUE THREAD

**Issue by dtickler-MF** [jolars/eulerr#110]
Hi there,

I'm trying to install eulerr on a PC running Windows 10, R version 4.3.0 & RStudio 2023.06.2+561.

Using command `devtools::install_github("jolars/eulerr")`, I get the error message

"Downloading GitHub repo jolars/eulerr@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/jolars/eulerr/tarball/HEAD'"

Any suggestions?

Thanks,

Dave

**Comment by jolars** [comment]
I cannot reproduce this. Does installing other packages through `install_github` work? Does `devtools::install_github("markvanderloo/tinytest")` work, for instance?

**Comment by dtickler-MF** [comment]
That failed with the following error:

Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found

  Did you spell the repo owner (`markvanderloo`) and repo name (`tinytest`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.

I may have a very localised problem - might ask colleagues if they are suffering the same issue!

**Comment by dtickler-MF** [comment]
Update - problem solved. Was a version of this problem https://community.rstudio.com/t/install-packages-unable-to-access-index-for-repository-try-disabling-secure-download-method-for-http/16578

**Comment by jolars** [comment]
Great! Thanks for reporting in any case.
