### ISSUE TITLE
Plotting issue when there are many groups

### ISSUE THREAD

**Issue by 1900mei** [jolars/eulerr#21]
When there are over 6 groups, the calculated fitted.value is set to 0 for some of the intersect area.
Code sample:
```
plot(euler(c(A = 2, B = 114, C = 42, D = 21, E = 13, F = 59, G = 8, 
             "A&B" = 5, "A&C" = 8, "A&D" = 2, "A&E" = 5, "A&F" = 21, "A&G" = 1)), 
     quantities = TRUE)
```
![image](https://user-images.githubusercontent.com/35851805/36319129-f6c69b72-130f-11e8-9cee-e565c6eac21c.png)
Group D and G are set aside when plotting.

**Comment by jolars** [comment]
As far as I can tell, this is not a bug. This diagram cannot be fit perfectly so the algorithm decides to place D and G outside because that minimizes the loss in the fit.

**Comment by jolars** [comment]
Also note that your specification also implicitly sets all higher-order intersections to 0.
