### ISSUE TITLE
Label regions with number of objects contained

### ISSUE THREAD

**Issue by mschubert** [jolars/eulerr#22]
Nice package, I particularly like that it adjusts for overlap size and doesn't require Java!

Is there a way to label all regions (either unique or overlapping) with the number of objects it contains?

**Comment by jolars** [comment]
Is the `quantities` argument to the `plot.euler()` function what you're looking for?

```
plot(euler(c(a = 1, b = 1, "a&b" = 0.5)),
     quantities = TRUE)
```
![image](https://user-images.githubusercontent.com/13087841/36629821-ebddd58e-195b-11e8-8882-2ad8dfb5b290.png)

**Comment by mschubert** [comment]
Yes! Thank you.

I should have looked at the documentation for `?plot.euler` instead of just `?plot`.

Could you maybe add this to Fig. 4 of the vignette too so it's more visible?

**Comment by jolars** [comment]
Yes, that's a good idea. Thanks!
