### ISSUE TITLE
Data only FALSE for category

### ISSUE THREAD

**Issue by greboul** [jolars/eulerr#23]
Hi,
Really nice package, very useful to create multiple Euler diagrams using categories with the by option.
But I have a problem since for some of my logical vectors, I have only FALSE values corresponding to one or multiple categories.
Is there a way to actually see that instead of having an error ( Error in stats::optimize(discdisc, interval = c(abs(r1 - r2), sum(r1,  : 'xmin' not less than 'xmax' )? Like a box with missing categories or something similar? 
Because the fact of missing TRUE values in some categories can be a very important result.
Hope it is possible, thanks !

**Comment by greboul** [comment]
Thanks for the update, I tried it but now I got this error:
"Error in pars[void, 1L] <- pars[!void, 1L]/sum(!void) :  number of items to replace is not a multiple of replacement length"
Thanks !

**Comment by jolars** [comment]
Can you please provide me with a reproducible example so that I can see what's going on?

**Comment by greboul** [comment]
Dear Jolars,
You will find attached in the eulerr_example.txt file the kind of data I have and I would like to see using Euler's graphs.
The file is a csv file with column names having 25 informative rows and 8 columns (7 logical and 1 factor).
It is representing presence or absence of taxa across 7 samples at high taxonomic rank (explaining why there is redundancy in taxa column).

### Here is my code throwing the error above: 
fit <- euler(dataDF, by=dataDF$taxa)

### What I am expecting is something like:
* __Opisthokonta__: S1=6,S2=2, S3=1,S4=1, S5=1,S6=1 (S3 and S4 share the same 1, which is different from the one of S5 and also of S6)
* __Stramenopiles__: S3=3
* __Hacrobia__: S2=1,S5=1, S6=1 (all 1 are samples specific -> expecting 3 shapes of same size not crossing) 
* __Excavata__: S2=1
* __Archaeplastida__: S1=3,S2=3,S3=2,S5=2,S6=2,S7=1 (one of the S3 is specific of S3 as well as one of S2 and two of S1. One is shared by all.)
* __Alveolata__: S7=2
[eulerr_example.txt](https://github.com/jolars/eulerr/files/1758896/eulerr_example.txt)

Hope this is understandable,
greboul

**Comment by jolars** [comment]
Does this look right?

![image](https://user-images.githubusercontent.com/13087841/36937508-dc3aec70-1f14-11e8-8a03-c353351db42c.png)

**Comment by greboul** [comment]
Seems pretty good, and I tried with my complete date and seems to work well.
Thanks a lot for your quick and great work !
