### ISSUE TITLE
request: option to provide lists as input

### ISSUE THREAD

**Issue by RvV1979** [jolars/eulerr#25]
Thanks for providing a great online tool!
It would be really useful if it were possible to only provide lists of items as input such that eulerr calculates the overlaps automatically, similar to what is possible here: http://bioinformatics.psb.ugent.be/webtools/Venn/

**Comment by jolars** [comment]
Please post any issues related to the web application at <https://github.com/jolars/eulerr.co> instead. This repository is for the R package.
