### ISSUE TITLE
the parameter of "ellipse"

### ISSUE THREAD

**Issue by xiexiaowei** [jolars/eulerr#26]
Hi,
Last year, I used your website and plot beautiful figures. Recently, the website updates. 

I have to install the eulerr by install.packages("eulerr") in my R interface,
When I set the parameter of "ellipse", it has no change. Because I don't want to show the area that is 0.
That's my code: 
library(eulerr)
fit=euler(c(
"A"=1,"B"=4,"C"=2,"A&B"=0,"A&C"=0,"B&C"=1,"A&B&C"=3))
plot(fit,fill=c("red","yellow","skyblue"),alpha=0.5,shape="ellipse",legend=T,quantities=TRUE)

How to solve this problem?
Thanks very much!

**Comment by jolars** [comment]
The shape parameter belongs to `euler()` not `plot.euler()`.  Try 
````
fit=euler(c("A"=1,"B"=4,"C"=2,"A&B"=0,"A&C"=0,"B&C"=1,"A&B&C"=3), shape = "ellipse")
````
