### ISSUE TITLE
Support titles using `main` argument in `plot.euler`.

### ISSUE THREAD

**Issue by jolars** [jolars/eulerr#27]

**Comment by vonjd** [comment]
Unfortunately the title doesn't show up in the plot. I also tried par(oma = c(0, 0, 5, 0)) to no avail.

What is strange is that last time I did this (about a year ago) it worked alright.

**Comment by vonjd** [comment]
Could you provide a small code example how to create a diagram with title? Thank you

**Comment by vonjd** [comment]
I also tried `title` but it gave me an error too: "Error in title(main) : plot.new has not been called yet"

**Comment by vonjd** [comment]
Ok so the following works:

```
fit1 <- euler(c("A" = A, "B" = B, "C" = C, "A&B" = AnB, "A&C" = A, "B&C" = B, "A&B&C" = AnB), input = "union")
plot1 <- plot(fit1, fill = c("red", "green", "gray90"))
grid.arrange(grobs = list(plot1), top = "test")
```

**Comment by j-andrews7** [comment]
Thanks, @vonjd, I had tried several options as well. Also feel a short example like this in the docs would be very helpful.
