### ISSUE TITLE
Implement non-proportional plots too

### ISSUE THREAD

**Issue by ripkrizbi** [jolars/eulerr#29]
Out of all venn implementations in R, yours is by far superior in terms of graphics output, correctly implementing the polygon clipping to render stacked polygons in accurate color. 

With this in mind, would it be possible to implement also the non-proportional layout of the diagram, just for the cases with highly overlapping categories and/or many categories, where the proportional layout is tricky to present all the combinations. This way, we could utilize your excellent graphics while presenting the complex or sparse venns.

Thanks in advance!

**Comment by jolars** [comment]
This is absolutely something I would like to do in the upcoming release but I currently do not have the time to implement this.
