### ISSUE TITLE
plot euler diagrams side by side using par()

### ISSUE THREAD

**Issue by Judithhhh** [jolars/eulerr#38]
Hello,

I am using the eulerr package, and I would like to plot several euler diagrams side by side using par().
for other plots this works fine, but when I plot the fit made with euler it doesn't work. 
fit1 is the endproduct of euler(...)

here I try to plot the same figure twice, next to eachother:

par(mfrow=c(1,2))
plot(fit1, quantities = TRUE)
plot(fit1, quantities = TRUE)

is there any way to do it?

kind regards,
Judith

**Comment by jolars** [comment]
eulerr uses grid graphics, not base graphics. Try `gridExtra::grid.arrange(plot(fit1), plot(fit2))`.

**Comment by Judithhhh** [comment]
Dear Jolars,

I have a follow-up question.
I would like to plot several plots next to eachother and each make them have a title.
How can I combine these two codes:

`gridExtra::grid.arrange(plot(euler1, quantities = TRUE),plot(euler2, quantities = TRUE))`

and
```
plot1 <- plot(euler1)
grid.arrange(grobs = list(plot1), top = "Title 1")
```

Kind regards, Judith

**Comment by jolars** [comment]
Use the `main` argument in `plot.euler()`, like so:

```r
library(eulerr)
library(gridExtra)

p1 <- plot(euler(c(A = 1)), main = "Foo")
p2 <- plot(euler(c(B = 1)), main = "Bar")
grid.arrange(p1, p2, ncol = 2)
```

![image](https://user-images.githubusercontent.com/13087841/48696331-f081af80-ebe1-11e8-8320-6d765f9cfb01.png)

**Comment by Judithhhh** [comment]
Thank you. it works now. 
before I also used the 'main' argument in 'plot', but it would never show the title, and I found this topic: https://github.com/jolars/eulerr/issues/27
but now it indeed works.
thank you for the quick reply. have a great day

**Comment by vonjd** [comment]
Unfortunately the titles don't show up in this example either... please advise - Thank you

**Comment by jolars** [comment]
What version of the package are you using @vonjd ?

**Comment by vonjd** [comment]
Oops... my bad: it works in v 5.1
