### ISSUE TITLE
datasets not available

### ISSUE THREAD

**Issue by eacgit** [jolars/eulerr#40]
I am just starting to use your package (thanks for the contribution) and find that the datasets are not available. On a separate note, I am not available to compile the newest code, but the binaries worked. (I am on an older Mac running OS X 10.10.5)  Thanks.

**Comment by jolars** [comment]
What data sets are not working? Please open a new issue for the compilation errors and paste what you are getting.

**Comment by eacgit** [comment]
Thanks for your quick reply.  I confirm that the dataset "organisms" is
_not_ available to me when I load the package.
Attached is a screenshot of a simple session where I load the package and
then try to use the dataset as you did.
The same happens with the other datasets (fruits, pain, plants).  The
screen shot includes details about the R version I am using.
I installed eulerr yesterday but could not compile for some reason so I
installed the slightly older binaries.  The version I have installed
is eulerr_3.1.0.

**Comment by jolars** [comment]
The datasets are available in the newest version of the package. I don't understand how you got the help files from the newest version but the binaries from the old version, but this is not an issue that is currently afflicting the latest version in any case.
