### ISSUE TITLE
shape = "ellipse" not working with matrix type

### ISSUE THREAD

**Issue by eacgit** [jolars/eulerr#41]
Apparently this issue was raised for list type (in #33) and it also applies to matrix type, meaning that setting shape = "ellipse" when applying euler(...) to a matrix does not change anything as compared to the default (shape = "circle).

**Comment by jolars** [comment]
I think you are wrong.

```r
plot(euler(organisms, shape = "ellipse"))
```

![image](https://user-images.githubusercontent.com/13087841/51710805-8a266c80-202a-11e9-96c8-e75242dd27bd.png)
