### ISSUE TITLE
confused by quantitities

### ISSUE THREAD

**Issue by jxchong** [jolars/eulerr#43]
Just came across your package while looking for a replacement for venneuler. I'm confused by your labels and drawings. It seems like the quantities it is showing are not disjoint? Given your example data fit1 in the vignette, I would expect to see that B and C are entirely contained with A, and I would also expect that C would have "0" that is in the section belonging only to C and similarly for B. Am I misunderstanding? Thanks!

```
fit1 <- euler(c("A" = 25, "B" = 5, "C" = 5,
                 "A&B" = 5, "A&C" = 5, "B&C" = 3,
                 "A&B&C" = 3))
```

**Comment by jolars** [comment]
See the documentation for the `input` argument in `euler()`.

```
library(euler)
fit1 <- euler(c("A" = 25, "B" = 5, "C" = 5,
                "A&B" = 5, "A&C" = 5, "B&C" = 3,
                "A&B&C" = 3),
              input = "union")
plot(fit1)
``` 

Is this what you expect?

![image](https://user-images.githubusercontent.com/13087841/53861775-6b31d780-3fe5-11e9-939d-c9e02daebc8e.png)

**Comment by jxchong** [comment]
Yes that's what I would expect. I see what I was doing wrong, I was giving the input="union" argument to the plot command instead of the fit command (which does not produce an error apparently but also does nothing!)  I had been attempting to run `plot(fit1, input="union")`

**Comment by jolars** [comment]
I can relate! I might introduce a solution to catch these mistakes in the future.
