### ISSUE TITLE
overlap between subsets not shown

### ISSUE THREAD

**Issue by jxchong** [jolars/eulerr#44]
Sorry - I have another question and after re-reading everything I still can't figure it out.

Regardless of whether I plot with ellipses or circles, A&C are never shown to overlap by 7501. Instead that intersection is shown to be contained entirely within B&C. There are other examples within the datasets (for example the quantity shown for D is wrong) but that's a prominent one.

```
plot(euler(
    c("A"=10487, "B"=13190, "C"=15675, "D"=3519,
    "A&B"=8302,
    "A&C"=7501,
    "A&D"=2986,
    "B&C"=10276,
    "B&D"=2914,
    "C&D"=0,
    "A&B&C"=5791,
    "A&B&D"=2511,
    "B&C&D"=0,
    "A&B&C&D"=0
    ),
    input = "union"
    ),
    quantities = TRUE,
    lty=1:4,
    legend=TRUE
)
```
![rplot](https://user-images.githubusercontent.com/1133838/53869284-c693a380-3fac-11e9-8706-5501cafebc5d.png)

**Comment by jxchong** [comment]
Here's the code I tried with disjoint

```
plot(euler(
    c("A"=0, "B"=0, "C"=3689, "D"=130,
    "A&B"=0,
    "A&C"=1710,
    "A&D"=475,
    "B&C"=4485,
    "B&D"=403,
    "C&D"=0,
    "A&B&C"=5791,
    "A&B&D"=2511,
    "B&C&D"=0,
    "A&B&C&D"=0
    ),
    input = "disjoint"
    ),
    quantities = TRUE,
    lty=1:4,
    legend=TRUE
)
```

**Comment by jolars** [comment]
That is because the algorithm couldn't find a perfect fit. As a rule of thumb, fit first using `euler()` and then analyze how well it fits before drawing conclusions and even plotting it. Sometimes it is only possible to get an approximate fit.

```
library(eulerr)
f <- euler(
  c(
    "A" = 0,
    "B" = 0,
    "C" = 3689,
    "D" = 130,
    "A&B" = 0,
    "A&C" = 1710,
    "A&D" = 475,
    "B&C" = 4485,
    "B&D" = 403,
    "C&D" = 0,
    "A&B&C" = 5791,
    "A&B&D" = 2511,
    "B&C&D" = 0,
    "A&B&C&D" = 0
  ),
  input = "disjoint",
  shape = "ellipse"
)
f

# original   fitted residuals regionError
# A              0   89.515   -89.515       0.004
# B              0  151.249  -151.249       0.008
# C           3689 3700.583   -11.583       0.007
# D            130  238.860  -108.860       0.005
# A&B            0  290.388  -290.388       0.015
# A&C         1710 1718.612    -8.612       0.003
# A&D          475  465.420     9.580       0.001
# B&C         4485 4475.234     9.766       0.010
# B&D          403  413.621   -10.621       0.000
# C&D            0    0.000     0.000       0.000
# A&B&C       5791 5780.875    10.125       0.013
# A&B&D       2511 2453.107    57.893       0.008
# A&C&D          0    0.000     0.000       0.000
# B&C&D          0    0.000     0.000       0.000
# A&B&C&D        0  212.572  -212.572       0.011
# 
# diagError: 0.015 
# stress:    0.002 
```

So you can see that there are some areas that are erroneously fit. You have to decide for yourself if the diagram is useful in spite of this.

```
plot(f, quantities = TRUE, lty = 1:4, legend = TRUE)
```
![image](https://user-images.githubusercontent.com/13087841/53886842-3cd1ed80-4021-11e9-9f95-2a945cc89dba.png)

**Comment by zx8754** [comment]
@jxchong Related/duplicate of issue https://github.com/jolars/eulerr/issues/32
