### ISSUE TITLE
Avoid text overlap

### ISSUE THREAD

**Issue by zx8754** [jolars/eulerr#45]
Example:

```R
library(eulerr)

x <- list(a = 1:10, b = 1:10)

fit <- euler(x, shape = "ellipse")
plot(fit, quantities = TRUE)
```

![image](https://user-images.githubusercontent.com/5212915/54274502-2b886400-4580-11e9-9ae5-4fd3a929ebf4.png)

**Comment by jolars** [comment]
I am broadening this issue to incorporate all instances where labels overlap, which is bad in general.
