### ISSUE TITLE
Wrong plot drawn using eulerr package

### ISSUE THREAD

**Issue by andyjslee** [jolars/eulerr#47]
Please try running the following:
```{r}
library(eulerr)

data <-  c(A = 500, 
           B = 400, 
           C = 400,
           "A&B" = 30, 
           "A&C" = 40, 
           "B&C" = 15, 
           "A&B&C" = 120)
fit <- euler(data, shape = "circle")
plot(fit,
     edge = TRUE,
     quantities = TRUE,
     labels = TRUE)
```
The intersection A&B&C (120) is not displayed at all. The problem goes away if I change the 'shape' parameter to "ellipse", but I want to keep the circle shape.

Fyi I'm using the latest version (5.1.0).

Thanks.

**Comment by jolars** [comment]
There is no guarantee that `eulerr` will produce a perfect fit. For many three-set combinations, there are no exact fits if you use circles. Please make sure to check the results of the fit before you decide to trust the plot. 

```r
fit

# original  fitted residuals regionError
# A          500 500.000     0.000       0.029
# B          400 400.000     0.000       0.023
# C          400 400.000     0.000       0.023
# A&B         30  30.000     0.000       0.002
# A&C         40  40.000     0.000       0.002
# B&C         15  14.999     0.001       0.001
# A&B&C      120   0.000   120.000       0.080
# 
# diagError: 0.08 
# stress:    0.025 
```

Clearly, the fit is not exact. You are stuck with using ellipses or going with some altogether different type of visualization.
