### ISSUE TITLE
add percentage to quantities

### ISSUE THREAD

**Issue by carlotta-93** [jolars/eulerr#48]
Hi,
First of all, thank you very much for this great package! 
I was wondering if it would be easy and/or useful to have the percentage printed as well as the numbers of elements in each set. 
Something maybe similar to the `print.mode = c("raw", "percent")` (from the VennDiagram package), to be added as parameter. 
So that the output would look like this:
<img width="358" alt="Screenshot 2019-04-23 at 11 37 48" src="https://user-images.githubusercontent.com/6638031/56570969-3f31dc00-65bc-11e9-8aa2-ab34b5348cad.png">

**Comment by Cumol** [comment]
I second this :)

Is there any hack to make this work?

**Comment by jolars** [comment]
@carlotta-93 and @Cumol, could you please see if #53 matches your expectations?
