### ISSUE TITLE
how to derive the label positions from an euler object? (former `label()` function)

### ISSUE THREAD

**Issue by g3o2** [jolars/eulerr#61]
In reference to #57, it appears that only the `coef()` function was reimplemented (see ellipses data.frame in the euler object) - thank you btw! - but no the `label()` function.

Or is there any other trick to derive the label positions from the euler object? AFAIR the now deprecated `label()` function exposed the coordinates necessary to position the text labels.

**Comment by jolars** [comment]
This was fixed in 774758e275cea5b826084435b72ce75bbd4d429c, simply do

```r
d <- plot(eulerr::euler(c(A = 1, B = 2)))
d$data
```

**Comment by g3o2** [comment]
@jolars Thank you!
