### ISSUE TITLE
Different euler diagrams on different runs

### ISSUE THREAD

**Issue by ArcticG** [jolars/eulerr#62]
Dear John Larsson,
Thank you for your help with eulerr package. The package is really useful and has been doing great with venn diagrams and 3 way euler diagrams.
I have noticed an issue with more complex euler diagrams in my hands, leading to reproducibility issue.

For example:  After running the same code 6 times I obtained somewhat different euler diagrams with the same data.  The resulting plots are shown as E1-E6 in below link with E3/E1 being the closest to the graph I was hoping for, but graphs like E2 being the most recurring ones:

https://ibb.co/DgcrK3H

Notes:
1. I also have included venn diagram of the same data on the top to show the expected relationship between groups.
2. (quantities = F) has not changed the variable output. 

I wonder if there is a way/option to make the results more consistent/reproducible for more complex euler diagrams.

I would be happy to answer any questions about system/setting used or send the raw data via email  if it would be helpful.
Thank you

**Comment by jolars** [comment]
I'm glad your finding it useful @ArcticG. Have you tried using `set.seed(some number)` ? It should make everything reproducible. Unfortunately, it's not otherwise possible to control the output since the results are based on optimization methods.

**Comment by ArcticG** [comment]
Thank you for your reply.
I tried setting various numbers as the seed. Indeed by assigning the seed a specific number (in my hand to 6) I can get the diagram I was hoping for consistently. 

I do not know know how much work it might require behind the scenes or if it would be feasible at all. But if it is possible, it might be helpful if have package prints out some sort of warning/notice in cases that it can not show all the overlapping regions due to space restrictions. 

Regardless, thank you again for your help and your helpful package.

**Comment by ArcticG** [comment]
Hello
Thank you for your reply. 
Please find below the diagrams generated using an identical seed (set.seed=6) for multiple consecutive(identical) runs. It seems the source of variation (in my hands) might be beyond the seed assignment. 

https://ibb.co/2sF6TL4

As a side suggestion, it would be really helpful if the package could notify/warn the user if certain overlapping areas could not be included in the plot. Although I do not know if it would be feasible/possible behind the scenes or worth the effort.  

I think for my applications, I will simply visually verify the generated diagrams from the package before using them. 

Thank you again for the package and your reply.
