### ISSUE TITLE
plot.euler border argument has no effect

### ISSUE THREAD

**Issue by geotheory** [jolars/eulerr#7]
As per title.  I'm using latest Mac/R.

Incidentally I tried installing eulerr dev version but that failed on Mac with:

```
ld: warning: directory not found for option '-L/usr/local/lib/gcc/x86_64-apple-darwin13.0.0/4.8.2'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [eulerr.so] Error 1
ERROR: compilation failed for package ‘eulerr’
* removing ‘/Users/robinedwards/Documents/R/library/3.3/eulerr’
* restoring previous ‘/Users/robinedwards/Documents/R/library/3.3/eulerr’
Error: Command failed (1)

```

**Comment by jolars** [comment]
Thank you. I'll fix the border issue in a moment. Regarding the compilation error I don't know what to tell you. it [works on the macosx setup on travis.ci](https://travis-ci.org/jolars/eulerr/jobs/212921259). Did you check [this](http://thecoatlessprofessor.com/programming/rcpp-rcpparmadillo-and-os-x-mavericks-lgfortran-and-lquadmath-error/), [this](http://stackoverflow.com/questions/25224325/compile-c-code-in-r-does-not-work-anymore), and [this](http://stackoverflow.com/questions/35999874/mac-os-x-r-error-ld-warning-directory-not-found-for-option)?
