### ISSUE TITLE
Cannot install package eulerr for R version 4.0.2

### ISSUE THREAD

**Issue by hectormonacci** [jolars/eulerr#72]
When I try to install package eulerr I get this error:

```package ‘eulerr’ is not available (for R version 4.0.2)```

My Linux distro (Void) has upgraded R from series 3 version to series 4.

Apparently package eulerr cannot be installed for R series 4.

Can you make the package available for R v4?

**Comment by jolars** [comment]
As you can see [here](https://cran.r-project.org/web/checks/check_results_eulerr.html), eulerr is available for R 4.0.2 (r-patched). (It also works fine to download on my end (R 4.0.2, ubuntu). 

Perhaps there's something fishy with your mirrors?
