### ISSUE TITLE
List method requires named vecotrs

### ISSUE THREAD

**Issue by gprezza** [jolars/eulerr#77]
This looks too trivial, but I can't seem to figure out if I am doing something wrong.

If using a list as input, the manual says: "Vectors in the list do not need to be named". However, this doesn't seem to be true:

```
my_list<- list(c("a","b","c"), c("a","d","e"))
euler(my_list)
```
gives:

```
Error in parse_list(combinations) : 
  !is.null(attr(combinations, "names")) is not TRUE
```

while 

```
my_list <- list(c("a","b","c"), c("a","d","e"))
names(my_list) <- c("name1", "name2")
euler(my_list)
```
runs succesfully.

Does the manual need updating?

**Comment by jolars** [comment]
you're right, thanks @gprezza !

**Comment by gprezza** [comment]
You're welcome!
