### ISSUE TITLE
Weird "0" overlaps

### ISSUE THREAD

**Issue by chilampoon** [jolars/eulerr#80]
Hi,
when I generating my venn diagram:

```
VennDiag <- euler(c("A" = 0, "B" = 8, "C" = 0, "A&B" = 7, 
                    "B&C" = 5, "A&C" = 0, "A&B&C" = 0))
```
The plot is like
![image](https://user-images.githubusercontent.com/43943114/113534872-e0df4780-959f-11eb-9eb4-9c45410ecb02.png)

```
> VennDiag
      original fitted residuals regionError
A            0  0.187    -0.187       0.009
B            8  8.077    -0.077       0.008
C            0  0.198    -0.198       0.010
A&B          7  6.946     0.054       0.013
A&C          0  0.000     0.000       0.000
B&C          5  4.921     0.079       0.011
A&B&C        0  0.261    -0.261       0.013

diagError: 0.013 
stress:    0.001 
```

So some of the overlapping regions in the plot are actually with 0 overlaps... 
Did I do something wrong? How can I resolve it? Thanks.

**Comment by chilampoon** [comment]
P.S the ideal plot should be like this 
![image](https://user-images.githubusercontent.com/43943114/113535233-dc675e80-95a0-11eb-802c-e8457babddc3.png)
and with __proportional__ circles

**Comment by jolars** [comment]
There is no guarantee that the resulting diagram is an exact fit when one is not possible. Try `shape = "ellipse"`.

**Comment by chilampoon** [comment]
Thanks, it works well after running several times
