### ISSUE TITLE
Cannot "unbold" labels

### ISSUE THREAD

**Issue by bersbersbers** [jolars/eulerr#94]
I don't seem to be able to print a label non-bold - is this intended, or am I too stupid too find it in the docs? :)

**Comment by jolars** [comment]
You can provide a list to the `labels` argument with various parameters. I think they are listed in a table in the documentation. The one you want is "font"

``` r
library(eulerr)

fit <- euler(c(A = 1))

plot(fit, labels = list(font = "normal"))
#> Warning in validGP(list(...)): NAs introduced by coercion
```

![](https://i.imgur.com/EGkpPjS.png)

<sup>Created on 2022-03-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by bersbersbers** [comment]
You are right, thanks! I had been looking for `fontstyle`, `fontface`, `fontweight`, ... but haven't tried the obvious. Sorry for the noise!
